---
extends:
- airbnb-base
- plugin:prettier/recommended
plugins:
- prettier
env:
  node: true
  mocha: true
rules:
  max-len:
  - error
  - code: 120
  no-console: 'off'
  func-names:
  - warn
  - never
  no-plusplus:
  - error
  - allowForLoopAfterthoughts: true
  no-underscore-dangle:
  - error
  - allow: ['_id']
  no-use-before-define:
  - error
  - functions: false
    classes: true
  prettier/prettier:
  - error
  - printWidth: 120
    singleQuote: true
overrides:
  files: "*.test.js"
  rules:
    no-unused-expressions: "off"
